---

- hosts: mysql
  become: true
  become_user: "{{ deployment_user }}"
  roles:
  - mysql

- hosts: simplesaml
  become: true
  become_user: "{{ deployment_user }}"
  roles:
  - simplesaml

- hosts: mediawiki
  become: true
  become_user: "{{ deployment_user }}"
  roles:
  - mediawiki

- hosts: mwlib
  become: true
  become_user: "{{ deployment_user }}"
  roles:
  - mwlib

- hosts: torquedata
  become: true
  become_user: "{{ deployment_user }}"
  roles:
  - torquedata
